### ISSUE TITLE
Lab Report 2 Feedback

### ISSUE THREAD

**Issue by farnaf** [mtang24/cse15l-lab-reports#2]
**Bug/Input 1**
- [x] Commit screenshot for bug/input 1
- [x] Link to test file for bug/input 1
- [x] Symptom shown as command + output for bug/input 1
- [x] Description of relationship between bug, symptom, and input for bug/input 1

**Bug/Input 2**
- [x] Commit screenshot for bug/input 2
- [x] Link to test file for bug/input 2
- [x] Symptom shown as command + output for bug/input 2
- [x] Description of relationship between bug, symptom, and input for bug/input 2

**Bug/Input 3**
- [x] Commit screenshot for bug/input 3
- [x] Link to test file for bug/input 3
- [x] Symptom shown as command + output for bug/input 3
  - screenshot: how is that the wrong terminal output for the third input? - feel free to respond in a comment below(:
- [x] Description of relationship between bug, symptom, and input for bug/input 3

Additional comments from your grader:
nice job 😃
Feel free to comment below if you have any questions about the rubric/feedback.

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by mtang24** [comment]
I consider the terminal output for the third input "wrong" because it doesn't print what is expected. What is expected is the arraylist containing the link(s) from the markdown file, but as shown in the output, I only get an empty arraylist printed before the code change. Essentially, an output is wrong if there IS some sort of link in the markdown file and it is NOT printed when running MarkdownParse. Let me know if that is the way I should be thinking about the symptom, which should be something that we don't expect our program to do.

**Comment by farnaf** [comment]
Ah I see. For this program, we expect getLinks() method to return only Markdown links (i.e., URLs that are formatted as md links with `()[]`). Your [third input](https://github.com/mtang24/markdown-parse/blob/main/test-file5.md?plain=1) has a URL, but it's not a Markdown link, and we don't expect it to be added to the output list. So I think the terminal output is actually correct.

**Comment by mtang24** [comment]
[Test file](https://github.com/mtang24/markdown-parse/blob/main/test-file5.md?plain=1)
[Lab report](https://mtang24.github.io/cse15l-lab-reports/lab-report-2-week-4.html)

Okay, I made an update to my lab report, but I'm still not sure what is considered the correct expected output. If we are only expecting a markdown link that is in the correct format of `()[]` , wouldn't that mean we only expect something to be added if it is already in the correct format? Like if it missing a `)` in the markdown file, that is wrong according to getLinks(), so it has to be fixed in order to work.

**Comment by farnaf** [comment]
The contents of the new test file are great!

If the input to getLinks() is `(test link)https://duckduckgo.com]` we expect an *empty* ArrayList. The output ArrayList would include https://duckduckgo.com only if the input was `[test link](https://duckduckgo.com)`

Your report looks good. Submit a regrade request on Gradescope, so I can update your grade(:

**Comment by mtang24** [comment]
Should I close this issue now?

**Comment by farnaf** [comment]
Remind me, did you make a regrade request? Did I update your grade on Gradescope?

**Comment by farnaf** [comment]
Ok yeah I forgot to close this
